services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    restart: always
    environment:
      POSTGRES_DB: olist
      POSTGRES_USER: olist_user
      POSTGRES_PASSWORD: olist_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/raw:/data/raw
      - ./sql:/sql

volumes:
  postgres_data:
